<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <AssemblyName>Sophos XGS Live Log Viewer</AssemblyName>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <Title>Sophos XGS Live Log Viewer by Benjamin Iheukumere | Safelink IT</Title>
    <Product>Sophos XGS Live Log Viewer by Benjamin Iheukumere | Safelink IT</Product>
    <Company>Benjamin Iheukumere</Company>
    <Authors>Benjamin Iheukumere</Authors>
    <Description>Windows desktop app for on-demand near-real-time Sophos XGS live log viewing over SSH.</Description>
    <Copyright>Copyright (c) 2026 Benjamin Iheukumere</Copyright>
    <Version>1.1.8</Version>
    <RepositoryUrl>https://github.com/BenjaminIheukumere/Sophos-XGS-Live-Log-Viewer</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2025.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\AppIcon.ico" />
    <Resource Include="Assets\AppIcon.png" />
  </ItemGroup>

</Project>
